### ISSUE TITLE
Is this being kept up to date with the OCaml code base at apache/thrift?

### ISSUE THREAD

**Issue by vthemelis** [vbmithr/ocaml-thrift-lib#4]
I see that this code base was ported from https://github.com/apache/thrift/tree/master/lib/ocaml . Are the two kept in sync?

**Comment by vbmithr** [comment]
They are not.

**Comment by vbmithr** [comment]
But I am working in a different OCaml implementation of thrift that is pretty much working, much more ocaml-y than this one. I might release it if you’re interested.

**Comment by vthemelis** [comment]
Hi, thanks for the quick reply!

> But I am working in a different OCaml implementation of thrift that is pretty much working, much more ocaml-y than this one. I might release it if you’re interested.

That would be great! It is convenient in some ways that the current implementation doesn't diverge too much from other language implementations but it is a bit clunky to work with in OCaml code.

**Comment by anuragsoni** [comment]
> But I am working in a different OCaml implementation of thrift that is pretty much working, much more ocaml-y than this one. I might release it if you’re interested.

@vbmithr I'd be interested in learning more about your new approach for ocaml-thrift. I've been exploring structured RPC solutions that support OCaml, and protobuf + a custom transport on top of async is the front runner for me so far, mostly because I'd like to use async and ocaml-thrift currently only provides a ocaml-threads based runtime. If there was a thrift based offering that is more ocaml-y and potentially supports (or makes it easy to provide a runtime) lwt/async etc i'd be happy to explore it.

**Comment by vbmithr** [comment]
Ok I will release the code.

**Comment by vbmithr** [comment]
https://github.com/deepmarker/thrift

I pushed it here. I don’t have time to write documentation or even comments, but basically there is a DSL in OCaml to describe thrift types similar to https://github.com/OCamlPro/ocplib-json-typed and a reader/writer for the compact format.

I wrote this while writing a library for the Parquet format (unreleased). Note that I only implemented the Thrift format, not the automatic RPC things. I do my RPC with Async-RPC personally.
